game:
  auto: True              # if true then steps at rate otherwise press space for each step          
  direct: False           # if true then direct control otherwise control through Markov inference
  cross: True             # allow snake to cross itself (no restricted states)
  rate: 5                 # steps per second 
  dimentions: [15, 15]    # world size.                   !!! numbers should be the same. nonsquare world is not supperted !!!
  pixels: [400, 400]      # initial resolution of the world in pixels (window could be resized)
dynamic:
  costString: abs x + abs y 
  limit: 15
  logging: False 
  maxStepsSearch: 5
snake:
  sizeInit: 5                 # initial length of the snake
  positionInit: [0, 0]        # initial position of the snake 
food:
  number: [2, 5]                        # range of foods number generated randomly
  rewards: [-5, 5]                      # range of food cost generated randomly
  exact:
    positions: [] #[[5, 5], [6, 6], [7, 7]]  # if empty then food gets generated randomly otherwise gameover after fst eaten
    costs: [] #[0, 3, 4]                     # if empty then food gets generated randomly 
